### ISSUE TITLE
Dependencies are ignored for browser builds

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/extension-scripts#7]
on this line, all dependencies are added to the exclusion list.

https://github.com/pixijs/extension-scripts/blob/main/lib/configs/rollup.mjs#L24

On npm builds it's okay, the package.json will list the dependencies and will be installed and then bundled when the final build is made.

On browsers, you don't have npm or any other way to fetch those needed libs so they need to be bundled with you.

**Comment by Zyie** [comment]
@bigtimebuddy I think I ran into the same issue here with pixi-ui

**Comment by bigtimebuddy** [comment]
Let me explain my rationale for this.

### Case 1: Bundle Dependencies

For example, [**pixi-svg**](https://github.com/bigtimebuddy/pixi-svg) is a plugin I created that uses these scripts. There are a bunch of utilities that I'm including in `devDependencies` (not `dependencies`). These utils automatically get bundled with the browser output AND these are added to `lib/external`. The utils I use for pixi-svg (`tinycolor2`, `d-path-parser`, etc) are rather feature-complete modules. I prefer that the dist and lib outputs have the same reproduction in the wild, since these are tested together. Doing this creates fewer issues where the dependency can change underneath. Also, when dependencies are added to `lib/external` the output is normalized (esm, cjs) which is handy.

### Case 2: Externalize Dependencies

There are, however, some examples where dependencies need to be externalized. Large utilities like `lodash` or libraries like `React` as well as PixiJS dependencies, shouldn't be inlined. These, however, need an entry in `extensionConfig. globals` defined to make sure the global for those thing is used correctly.

### Case 3. [Proposed] Bundle Browser Dependencies, Externalize Module Dependencies

What you're proposing is another case where the module output (i.e., lib) treat dependencies as external node_modules, but browser builds (i.e., dist) bundles the dependencies. I don't really like this pattern because it creates opportunities for users to have difference experiences depending on which output is consumed. It makes it harder to validate bugs that originate from external modules. Again, this is my preference in seeing how different plugins use dependencies.

Without breaking Cases 1 or 2, we could add a new `extensionConfig` property (e.g., `bundleDependencies`) which the developer would provide a list of a dependencies that are _only_ bundled for the browser output.

**Comment by miltoncandelero** [comment]
Woah, but we are going against the definition for the fields in package.json

- `devDependencies` should NEVER be bundled with anything. You put things that are needed when somebody want to collaborate developing a library (example: `typescript`, `eslint`, `rollup`). You shouldn't `require` or `import` anything from your `devDependencies` (`import types` in typescript is an exception, as it disappears during build time)

- `dependencies` are things that your app relies so hard upon that it bundles them (in browsers) or downloads them when installed. your library wants to have a copy of that just for yourself so you hard depend on them. (example: `earcut` or `is-mobile` for pixijs)

- `peerDependencies` are when you need to "share" the same version of a lib that everyone else is using (example: `@pixi/sound` needs to be in a pixi environment but can't bring a copy of pixi with itself) usually because you are enhancing or building on top of it. That is where globals come in for browsers where you don't have a package manager to connect all those "softer" dependencies.

Finally, when you do something like `npm i @pixi/svg` these things happen: 
- npm installs your `dependencies` so you have exactly what you asked for
- npm checks that you manually installed your `peerDependencies` or warns/errors you because you are in a "broken" state. 
- npm **does not** install your `devDependencies`

Your `devDependencies` only get installed if you clone the project (say `npm i @pixi/svg`) and run `npm install` and gets you ready to develop.

I don't think we can have an actionable path since we are using the fields in the package.json differently 😅 

I think we can close this now 😅

**Comment by bigtimebuddy** [comment]
I'm not doing anything to violates the standard definitions of devDependencies, dependencies or peerDependencies. The _shipped code_ and package.json that's include is consistent with everything you said. I'm using devDependencies as part of the _build_ process to specify which  bits of code are _inlined_ or _bundled_. This is no different than, say, Babel plugins adding in transpiled code, or tslib, or other runtime bits.

Whether you bundle/inline or dynamically link dependencies, there's not a correct answer. What matters is the code that's actually shipped to developers. It's fine if you prefer Case 3 in your plugins. That approach, for me, introduces more problems between bundlers/browsers which is why I don't prefer it.
